name: 'unity-ci-self-hosted-uploader'
description: 'Unity CI self-hosted uploading action'
author: 'Marco Selleri <marco.selleri96@gmail.com>'

branding:
  icon: 'heart'
  color: 'blue'

inputs:
  buildFolderFullPath: 
      description: 'Full path of the build folder to zip'
      required: true
  archiveFileName: 
    description: 'Name of the file to upload. Generated after zippping the build folder'
    required: true
  archiveFolder: 
    description: 'Loation where to temporary save the archive'
    required: false
  zipCompressionLevel: 
    description: 'Compression level of the zip file. Allowed values: 0-9'
    required: false
    default: '9'

  storage: 
    description: 'Which storage to use for the upload. Allowed values: "google", "local"'
    required: true
    default: 'google'

  localDestinationFolder: 
    description: 'Destination folder for the local storage. Required if storage is set to "local"'
    required: false

  googleOauthClientId: 
    description: 'Google OAuth client ID. Required if storage is set to "google"'
    required: false
  googleOauthClientSecret: 
    description: 'Google OAuth client secret. Required if storage is set to "google"'
    required: false
  googleOauthRedirectUri: 
    description: 'Google OAuth redirect URI. Required if storage is set to "google"'
    required: false
  googleOauthRefreshToken: 
    description: 'Google OAuth refresh token. Required if storage is set to "google"'
    required: false
  googleFolderId: 
    description: 'Google Drive folder ID. Required if storage is set to "google"'
    required: false
  
runs:
  using: node20
  main: dist/index.js
